host_passwords:
  /docker-runner-ansible-ssh-node-1: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32636435326266376135616166633761663536303738353630623435353836623166663265346537
    3338313766333964306232613763383032326633373163300a656662356138383136656438336463
    61306130656162336531353633616362313261363935316331363935366461646434386333306639
    3263306639656464370a613135346132326664326335323965346639383861356233343039313530
    3038
  /docker-runner-ansible-ssh-node-2: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32636435326266376135616166633761663536303738353630623435353836623166663265346537
    3338313766333964306232613763383032326633373163300a656662356138383136656438336463
    61306130656162336531353633616362313261363935316331363935366461646434386333306639
    3263306639656464370a613135346132326664326335323965346639383861356233343039313530
    3038

host_users:
  /docker-runner-ansible-ssh-node-1: rundeck
  /docker-runner-ansible-ssh-node-2: rundeck